# Generated by Django 5.2.4 on 2025-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_old_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_telegram',
            field=models.BooleanField(default=False, verbose_name='Отримувати сповіщення в Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
